[bin/analysis-scripts] improve shell scripts thanks to shellcheck

diff --git a/bin/frama-c-script b/bin/frama-c-script
--- a/bin/frama-c-script
+++ b/bin/frama-c-script
@@ -22,7 +22,7 @@
 ##########################################################################
 
 # Accept '-check' to avoid issues with ptests
-while [ $# -ge 1 -a "$1" = "-check" ]; do
+while [ $# -ge 1 ] && [ "$1" = "-check" ]; do
     shift
 done
 
@@ -78,7 +78,7 @@ usage() {
    echo "      Applies some transformations to an existing compile_commands.json"
    echo "      (such as relativizing paths) to improve portability."
    echo "      [default: ./compile_commands.json]"
-   exit $1
+   exit "$1"
 }
 
 if [ $# -lt 1 ]; then
@@ -141,11 +141,7 @@ flamegraph() {
         dir="$FRAMAC_SESSION"
     fi
     if [ ! -d "$dir" ]; then
-        mkdir "$dir"
-        if [ $? -ne 0 ]; then
-            echo "error: could not create '$dir'"
-            exit 1
-        fi
+        mkdir "$dir" || { echo "error: could not create '$dir'"; exit 1; }
     fi
     out_svg="$dir/flamegraph.svg"
     "${FRAMAC_SHARE}/analysis-scripts/flamegraph.pl" \
@@ -179,7 +175,7 @@ configure_for_frama_c() {
         echo "error: 'configure' command requires a machdep";
         exit 1
     fi
-    MACHDEP="$(echo $1 | tr a-z A-Z)"
+    MACHDEP=${1^^} # to uppercase
     shift
     CPP="gcc -E -nostdinc -fno-builtin -I${FRAMAC_SHARE}/libc -D__FC_MACHDEP_${MACHDEP}" ./configure "$@"
 }
@@ -190,22 +186,22 @@ case "$command" in
         ;;
     "make-template")
         shift;
-        ${FRAMAC_SHARE}/analysis-scripts/make_template.py "$@";
+        "${FRAMAC_SHARE}"/analysis-scripts/make_template.py "$@";
         ;;
     "list-files")
         shift;
-        ${FRAMAC_SHARE}/analysis-scripts/list_files.py "$@";
+        "${FRAMAC_SHARE}"/analysis-scripts/list_files.py "$@";
         ;;
     "list-functions")
         shift;
         # to avoid a slow startup, we only load plugins which perform syntactic
         # transformations. This may trigger annotation errors due to missing
         # plugins, so we disable those
-        ${DIR}/frama-c "$@" -no-autoload-plugins -load-module variadic,instantiate,${FRAMAC_SHARE}/analysis-scripts/list_functions.ml -kernel-warn-key annot-error=inactive -kernel-verbose 0;
+        "${DIR}"/frama-c "$@" -no-autoload-plugins -load-module variadic,instantiate,"${FRAMAC_SHARE}"/analysis-scripts/list_functions.ml -kernel-warn-key annot-error=inactive -kernel-verbose 0;
         ;;
     "find-fun")
         shift;
-        ${FRAMAC_SHARE}/analysis-scripts/find_fun.py "$@";
+        "${FRAMAC_SHARE}"/analysis-scripts/find_fun.py "$@";
         ;;
     "flamegraph")
         shift;
@@ -213,7 +209,7 @@ case "$command" in
         ;;
     "summary")
         shift;
-        ${FRAMAC_SHARE}/analysis-scripts/summary.py "$@";
+        "${FRAMAC_SHARE}"/analysis-scripts/summary.py "$@";
         ;;
     "configure")
         shift;
@@ -221,11 +217,11 @@ case "$command" in
         ;;
     "make-wrapper")
         shift;
-        ${FRAMAC_SHARE}/analysis-scripts/make_wrapper.py "$0" "$@";
+        "${FRAMAC_SHARE}"/analysis-scripts/make_wrapper.py "$0" "$@";
         ;;
     "normalize-jcdb")
         shift;
-        ${FRAMAC_SHARE}/analysis-scripts/normalize_jcdb.py "$@";
+        "${FRAMAC_SHARE}"/analysis-scripts/normalize_jcdb.py "$@";
         ;;
     *)
         echo "error: unrecognized command: $command";
