Removes some TABs in share/Makefile.linting

diff --git a/share/Makefile.linting b/share/Makefile.linting
--- a/share/Makefile.linting
+++ b/share/Makefile.linting
@@ -89,26 +89,26 @@ endif
 
 .lint/check-ocp-indent-version:
 	if command -v $(OCP_INDENT) >/dev/null; then \
-		if [ -z "$(shell $(OCP_INDENT) --version)" ]; then echo "warning: $(OCP_INDENT) returned an empty string, assuming it is the correct version"; \
-		else \
-			$(eval ocp_version_major := $(shell $(OCP_INDENT) --version | $(SED) -E "s/^([0-9]+)\.[0-9]+\..*/\1/")) \
-			$(eval ocp_version_minor := $(shell $(OCP_INDENT) --version | $(SED) -E "s/^[0-9]+\.([0-9]+)\..*/\1/")) \
-			if [ "$(ocp_version_major)" -lt 1 -o "$(ocp_version_minor)" -lt 7 ]; then \
-				echo "error: $(OCP_INDENT) 1.7.0 required for linting (got $(ocp_version_major).$(ocp_version_minor))"; \
-			exit 1; \
-			fi; \
-		fi; \
-	else \
-		exit 1; \
-	fi;
+          if [ -z "$(shell $(OCP_INDENT) --version)" ]; then echo "warning: $(OCP_INDENT) returned an empty string, assuming it is the correct version"; \
+          else \
+            $(eval ocp_version_major := $(shell $(OCP_INDENT) --version | $(SED) -E "s/^([0-9]+)\.[0-9]+\..*/\1/")) \
+            $(eval ocp_version_minor := $(shell $(OCP_INDENT) --version | $(SED) -E "s/^[0-9]+\.([0-9]+)\..*/\1/")) \
+            if [ "$(ocp_version_major)" -lt 1 -o "$(ocp_version_minor)" -lt 7 ]; then \
+              echo "error: $(OCP_INDENT) 1.7.0 required for linting (got $(ocp_version_major).$(ocp_version_minor))"; \
+              exit 1; \
+            fi; \
+          fi; \
+        else \
+          exit 1; \
+        fi;
 	$(MKDIR) $(dir $@)
 	$(TOUCH) $@
 
 .lint/check-clang-format-installed:
 	if ! command -v $(CLANG_FORMAT) >/dev/null; then \
-		echo "error: $(CLANG_FORMAT) must be installed"; \
-		exit 1; \
-	fi;
+          echo "error: $(CLANG_FORMAT) must be installed"; \
+          exit 1; \
+        fi;
 	mkdir -p $(dir $@)
 
 ###############
@@ -151,7 +151,7 @@ LINT.clean-targets+= \
 
 # Same list on both lines
 LINT.clean-targets+= \
-	clean-check-indent
+        clean-check-indent
 .PHONY: clean-check-indent
 
 # Generic rule
