[docs] Initial setup for building doxygen documentation

diff --git a/src/plugins/e-acsl/Makefile.in b/src/plugins/e-acsl/Makefile.in
--- a/src/plugins/e-acsl/Makefile.in
+++ b/src/plugins/e-acsl/Makefile.in
@@ -278,3 +278,16 @@ endif
 
 $(E_ACSL_DIR)/Makefile: $(E_ACSL_DIR)/Makefile.in $(CONFIG_STATUS_DIR_DEP)
 	cd $(CONFIG_STATUS_DIR) && ./config.status
+
+#####################################
+# Doxygen 													#
+#####################################
+DOXYGEN = @DOXYGEN@
+doxygen:
+	if ! test $(DOXYGEN) = "no"; then \
+		$(DOXYGEN) doc/doxygen/doxygen.cfg ; \
+	else \
+	  echo "Warning: Skip doxygen documentation: Doxygen executable not found."; \
+	fi
+
+doc:: doxygen
